# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  schedule: [{cron: "0 */3 * * *"}]  # every 3 hours
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true

    steps:
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@master   # use master for post-2024 API fixes
        with:
          token: ${{ secrets.GH_PAT }}

          user: Kydoimos97
          template: classic
          base: header, activity, community, metadata
          base_indepth: yes
          config_timezone: America/Denver
          repositories_affiliations: owner, collaborator, organization_member
          repositories_forks: no

          plugin_languages: yes
          
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          # ğŸ“ˆ Traffic / Visitors
          # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          plugin_traffic: yes

          # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          # âŒ¨ï¸ WakaTime Integration
          # â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects-graphs, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, json
          plugin_wakatime_days: 365

          users_ignored: github-actions[bot], dependabot[bot], copilot[bot], copilot-chat[bot]
